### ISSUE TITLE
bug: error will not be displayed

### ISSUE THREAD

**Issue by Xu-pixel** [PunGrumpy/logixlysia#24]
### Did you use latest version?

- [X] I have checked the latest version.

### Platform

🪟 Windows

### Priority

🚧 Medium

### Description

```Markdown
error will not be displayed in elysia >= v1.0.4 .
however, i add `{ as: 'global' }` to onError() function in index.ts , it worked.
And another problem is when return an error(elysia offical), it will still display info green 200 .
```

**Comment by Xu-pixel** [comment]
if use throw error
![image](https://github.com/PunGrumpy/logixlysia/assets/58813571/51aa1fa2-5c45-41ba-a9ff-31f048e36ab1)
it will display error but 200
![image](https://github.com/PunGrumpy/logixlysia/assets/58813571/cac73ff1-6d91-4b34-934c-f5c79bad1e9f)

**Comment by PunGrumpy** [comment]
Thank you for this issue 🙏

In `onError` it doesn't show, I fixed it!
But when using `throwError` and giving a status of `200`, I'm not sure because I get the value `data` from **Elysia** returns.

**Comment by Xu-pixel** [comment]
Thank you for your efficient response！ I really appreciate your quick attention to this matter.
And  for the problems show in picture I think it should wait **Elysia**
🙏

**Comment by PunGrumpy** [comment]
@Xu-pixel Now I fixed it, hope it works. But as far as I try in my machine it works. Sorry for not telling you

![Logixlysia Example with throw error](https://github.com/PunGrumpy/logixlysia/assets/108584943/9daffadc-bd86-4214-9a6e-8bf48b28bcd8)

**Comment by Xu-pixel** [comment]
Thank you very much ! in elysia v1.0.13,it can log all requests but still cannot handle correct status code.However,now it is enough for my project.
![image](https://github.com/PunGrumpy/logixlysia/assets/58813571/1b94eed2-e68c-48b7-a456-492c0da1b596)
Thanks for your works again ! I think you should recommand your repo in **Elysia** offical site, have not seen logixlysia list in the 3rd part plugin
![image](https://github.com/PunGrumpy/logixlysia/assets/58813571/409cedf0-0acf-4f97-a19f-76a8c909ae9e)

**Comment by PunGrumpy** [comment]
Thanks mate for the issue in my repo ❤️ for the 3rd party plugin on Elysia's website, if I have free time I will add it.
